name: Production CD

on:
  pull_request:
    branches: [master]
    types: [closed]


jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on : [self-hosted, builder]
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t techmutant/mydockerrepo .
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker push techmutant/mydockerrepo
      - run: |
          docker compose pull
          docker compose up -d
          docker compose restart