name: Staging test
on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - name: nodejs
        run: docker build -t techmutant/mydockerrepo .
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker push techmutant/mydockerrepo
