name: Staging test

on:
  push:
    branches: [master]
    
jobs:
    test:
        runs-on: [ self-hosted, nodebuilder ]
        steps:
          - uses: actions/checkout@v3
          - name: nodejs
            run: docker build -t helloworld .
